language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: syd-baroya-github
    token:
      secure: 1f87330c664245cd3f2ed1a7690937f0c08ee507
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
